language: ruby
before_install:
  - gem install bundler

install:
  - bundle install --without debugger

cache: bundler

script:
  - bundle exec ruby test/suite.rb

notifications:
  email:
  - ngiger@ywesee.com
rvm:
  - ruby-head
  - 2.1.3
  - 2.0.0
  - 1.9.3
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 1.8.7
