language: ruby
before_install:
  - gem install bundler

install:
  - bundle install --without debugger

cache: bundler

script:
  - bundle exec ruby test/suite.rb

notifications:
  email:
  - ngiger@ywesee.com
rvm:
  - 2.1.3
  - 2.0.0
  - 1.9.3
  - 1.8.7
